# ============================================
# EMBEDDING SERVICE — FASTEMBED (LOCAL, LOW MEMORY, NO NETWORK CALLS)
# ============================================
#
# WHY THIS VERSION EXISTS (history, for future-you):
# v1: loaded sentence-transformers locally -> pulled in torch -> OOM
#     on Render's 512MB free tier.
# v2: switched to HF's hosted Inference API (api-inference.huggingface.co)
#     to avoid loading torch -> but HF deprecated that exact endpoint
#     in favor of a new "Inference Providers" system (router.huggingface.co)
#     that doesn't reliably support arbitrary feature-extraction models,
#     so DNS lookups for the old domain now fail outright.
# v3 (this file): fastembed — Qdrant's own embedding library. It runs
#     the model locally via ONNX Runtime instead of PyTorch. The ONNX
#     build of multilingual-e5-small is ~130MB (vs. torch + the model
#     being 800MB+), so it fits comfortably in 512MB RAM, and there
#     are no per-query network calls — the model is downloaded once
#     (from the regular huggingface.co model hub, not the broken
#     api-inference subdomain) and cached in the Docker image/layer.

import os
import numpy as np
import hashlib
from fastembed import TextEmbedding

# ============================================
# MODEL SETUP
# ============================================
# fastembed maintains its own list of supported models — this one is
# officially supported and matches the model the collection was
# originally sized for (384-dim, in vector_store.ensure_collection).
MODEL_NAME = os.environ.get("EMBEDDING_MODEL", "BAAI/bge-small-en-v1.5")

print(f"📥 Loading local ONNX embedding model: {MODEL_NAME}")
_model = TextEmbedding(model_name=MODEL_NAME)
print("✅ Embedding model loaded (ONNX Runtime — no torch, no network calls).")

# ============================================
# CACHE SETUP
# ============================================
# Unchanged in spirit from earlier versions — disk cache, not RAM,
# so it was never part of the memory problem. Still useful here to
# skip re-computing embeddings for repeated identical queries.
CACHE_DIR = "data/cache/embeddings"
os.makedirs(CACHE_DIR, exist_ok=True)


def _get_cache_key(texts):
    # Include the model name so switching embedding models never silently
    # reuses cached vectors generated by a different model (which would
    # produce a dimension mismatch or, worse, subtly wrong embeddings).
    combined = MODEL_NAME + "||" + "||".join(texts)
    return hashlib.md5(combined.encode()).hexdigest()


def _get_cached_embeddings(key):
    cache_file = os.path.join(CACHE_DIR, f"{key}.npy")
    if os.path.exists(cache_file):
        return np.load(cache_file).tolist()
    return None


def _save_embeddings(key, embeddings):
    cache_file = os.path.join(CACHE_DIR, f"{key}.npy")
    np.save(cache_file, np.array(embeddings))


# ============================================
# MAIN EMBEDDING FUNCTION
# ============================================
def get_embeddings(texts):
    """
    Generate embeddings for a list of texts using the local ONNX model,
    with on-disk caching so repeated identical inputs are free.

    Note on E5 models: the multilingual-e5-small model was trained with
    "query: " / "passage: " prefixes for best retrieval accuracy (the
    idea is the model learns different representations for search
    queries vs. the documents being searched). This function does NOT
    add those prefixes — it treats every input the same way, matching
    how the original local sentence-transformers version behaved, so
    ingestion and querying stay consistent with each other. If you
    want to squeeze out extra retrieval quality later, fastembed
    exposes model.query_embed() (adds "query: ") separately from
    model.embed() (adds "passage: ") — but that requires calling this
    function differently for ingestion vs. querying, so it's a
    deliberate follow-up, not something to change quietly here.

    Returns: list of embedding vectors (list of floats), one per input text.
    Returns [] if texts is empty or if generation fails.
    """
    if not texts:
        return []

    cache_key = _get_cache_key(texts)
    cached = _get_cached_embeddings(cache_key)
    if cached is not None:
        print(f"✅ Using cached embeddings for {len(texts)} texts")
        return cached

    print(f"🔄 Generating embeddings for {len(texts)} texts locally (fastembed)...")

    try:
        # model.embed() returns a generator of numpy arrays, one per input
        embeddings = list(_model.embed(texts))
        embeddings_list = [e.tolist() for e in embeddings]
    except Exception as e:
        print(f"❌ Embedding generation failed: {e}")
        return []

    _save_embeddings(cache_key, embeddings_list)
    print(f"✅ Generated {len(embeddings_list)} embeddings")
    return embeddings_list